# Generated by Django 5.2.7 on 2025-10-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_job_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
